split_mesh: split_mesh.cpp
	g++ -std=c++11 -I /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/metis/5.1.0/include -L libmetis.a -lmetis -o split_mesh split_mesh.cpp

clean:
	rm *.dat out_* *_Mille* 
