#!/usr/bin/bash

#Lecture du fichier INPUT_MONTE_CARLO
let i=0
rm slurm*
while read -r line;do
  if [ $i -ge 1 ];then
    debit=`echo $line | cut -d " " -f 1`
    hamont=`echo $line | cut -d " " -f 2`
    haval=`echo $line | cut -d " " -f 3`
    maning=`echo $line | cut -d " " -f 4`
    echo "Cas $i $debit $hamont $haval $maning"

    if [ ! -d multi_$i ]; then 
      mkdir multi_$i
    fi
    cd multi_$i
    cp ../base_files/*_Mille* .
    cp ../base_files/runfile .
    cp ../base_files/makefile .
    cp ../base_files/*liens* .
    ../gen_donnees $debit $hamont $haval $maning
    echo "Cleaning folder multi_$i"
    make clean
    cd ..
  else
    nb=$line
  fi
  let i=$i+1
done < $1
