#!/usr/bin/bash


#Lecture du fichier INPUT_MONTE_CARLO
let i=0
while read -r line;do
  if [ $i -ge 1 ];then
    debit=`echo $line | cut -d " " -f 1`
    hamont=`echo $line | cut -d " " -f 2`
    haval=`echo $line | cut -d " " -f 3`
    maning=`echo $line | cut -d " " -f 4`
    echo "Cas $i $debit $hamont $haval $maning"

    if [ ! -d multi_$i ]; then 
      mkdir multi_$i
    fi
    cd multi_$i
    cp ../base_files/* .
    ../gen_donnees $debit $hamont $haval $maning
    mv 4_gpu.sh 4_gpu_multi_$i.sh
    sbatch 4_gpu_multi_$i.sh
    cd ..
  else
    nb=$line
    #echo $nb
  fi
  let i=$i+1
done < "INPUT_MONTE_CARLO.dat"

