main: main.cpp
	g++ -std=c++11 -I /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/metis/5.1.0/include -L libmetis.a -lmetis -o main main.cpp

main2: main2.cpp
	g++ -std=c++11 -I /cvmfs/soft.computecanada.ca/easybuild/software/2017/avx2/Compiler/gcc5.4/metis/5.1.0/include -L libmetis.a -lmetis -o main2 main2.cpp

clean:
	rm *.dat out_* *_Mille* 
